---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 11.4.4

platforms:
- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
    network:
    - [private_network, ip: 33.33.33.10]
    customize:
      cpus: 2
      memory: 1024
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    network:
    - [private_network, ip: 33.33.33.10]
    customize:
      cpus: 2
      memory: 1024
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
    network:
    - [private_network, ip: 33.33.33.10]
    customize:
      cpus: 2
      memory: 1024
  run_list:
  - recipe[apt]
suites:
- name: disable
  run_list:
    - recipe[apparmor]
    - recipe[minitest-handler]
- name: enable
  run_list:
     - recipe[apparmor]
     - recipe[minitest-handler]
  attributes:
    apparmor:
      disable: false
